- name: Facts
  debug:
    var: ansible_facts.ansible_local

- name: Generate servers's privkey if not exists
  shell: wg genkey
  register: server_privkey
  when: ansible_facts.ansible_local.interface.privkey is undefined

- name: Save privkey
  set_fact:
    ansible_facts:
      ansible_local:
        interface:
          privkey: "{{ server_privkey.stdout }}"
  when: ansible_facts.ansible_local.interface.privkey is undefined
  notify:
    - update_local_facts
    - reload_local_facts

- name: Facts
  debug:
    var: ansible_facts.ansible_local

- name: Generate servers's pubkey if not exists
  shell: "echo {{ server_privkey.stdout }} | wg pubkey"
  register: server_pubkey
  when: ansible_facts.ansible_local.interface.pubkey is undefined

- name: Save pubkey
  set_fact:
    ansible_facts:
      ansible_local:
        interface:
          pubkey: "{{ server_pubkey.stdout }}"
  when: ansible_facts.ansible_local.interface.pubkey is undefined
  notify:
    - update_local_facts
    - reload_local_facts

- name: Debug
  debug:
    var: ansible_facts.ansible_local | to_json