wireguard_mtu: 1420
wireguard_netaddr: 10.200.200.0
wireguard_netmask: 24
wireguard_interface_address: "{{ wireguard_netaddr | ansible.utils.ipsubnet(wireguard_netmask) | ansible.utils.ipaddr('next_usable') }}/{{ wireguard_netmask }}"
wiregurad_if_name: wg0

networks: {}

groups:
  admins:
    allowed_nets: []
    disallowed_nets: []
    members: []