wireguard_mtu: 1420
wireguard_address: 10.200.200.1
wireguard_network: 10.200.200.0
wireguard_mask: 24
wiregurad_if_name: wg0

networks: {}

groups:
  admins:
    allowed_nets: []
    disallowed_nets: []
    members: []